title: "Refined WaveNet Vocoder for Variational Autoencoder Based Voice Conversion"
logo: /imgs/proposed.png
description: "Demo page for paper: Refined WaveNet Vocoder for Variational Autoencoder Based Voice Conversion"
theme: jekyll-theme-minimal
